// Generated by gencpp from file pr2_mechanism_msgs/UnloadControllerRequest.msg
// DO NOT EDIT!


#ifndef PR2_MECHANISM_MSGS_MESSAGE_UNLOADCONTROLLERREQUEST_H
#define PR2_MECHANISM_MSGS_MESSAGE_UNLOADCONTROLLERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pr2_mechanism_msgs
{
template <class ContainerAllocator>
struct UnloadControllerRequest_
{
  typedef UnloadControllerRequest_<ContainerAllocator> Type;

  UnloadControllerRequest_()
    : name()  {
    }
  UnloadControllerRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UnloadControllerRequest_

typedef ::pr2_mechanism_msgs::UnloadControllerRequest_<std::allocator<void> > UnloadControllerRequest;

typedef boost::shared_ptr< ::pr2_mechanism_msgs::UnloadControllerRequest > UnloadControllerRequestPtr;
typedef boost::shared_ptr< ::pr2_mechanism_msgs::UnloadControllerRequest const> UnloadControllerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator1> & lhs, const ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator1> & lhs, const ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pr2_mechanism_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_mechanism_msgs/UnloadControllerRequest";
  }

  static const char* value(const ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The UnloadController service allows you to unload a single controller \n"
"# that is loaded in pr2_controller_manager. \n"
"\n"
"# To unload a controller, specify the \"name\" of the controller. \n"
"# The return value \"ok\" indicates if the controller was unloaded or not.\n"
"# There are three cases when unloadinng a controller will fail:\n"
"#  * No controller with the specified name exists\n"
"#  * The controller is still running\n"
"#  * Another controller depends on the specified controller\n"
"\n"
"string name\n"
;
  }

  static const char* value(const ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UnloadControllerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_mechanism_msgs::UnloadControllerRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_MECHANISM_MSGS_MESSAGE_UNLOADCONTROLLERREQUEST_H
