// Generated by gencpp from file pr2_controllers_msgs/JointControllerStateArray.msg
// DO NOT EDIT!


#ifndef PR2_CONTROLLERS_MSGS_MESSAGE_JOINTCONTROLLERSTATEARRAY_H
#define PR2_CONTROLLERS_MSGS_MESSAGE_JOINTCONTROLLERSTATEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <pr2_controllers_msgs/JointControllerState.h>

namespace pr2_controllers_msgs
{
template <class ContainerAllocator>
struct JointControllerStateArray_
{
  typedef JointControllerStateArray_<ContainerAllocator> Type;

  JointControllerStateArray_()
    : header()
    , controllestate()  {
    }
  JointControllerStateArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , controllestate(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::pr2_controllers_msgs::JointControllerState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pr2_controllers_msgs::JointControllerState_<ContainerAllocator> >::other >  _controllestate_type;
  _controllestate_type controllestate;





  typedef boost::shared_ptr< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> const> ConstPtr;

}; // struct JointControllerStateArray_

typedef ::pr2_controllers_msgs::JointControllerStateArray_<std::allocator<void> > JointControllerStateArray;

typedef boost::shared_ptr< ::pr2_controllers_msgs::JointControllerStateArray > JointControllerStateArrayPtr;
typedef boost::shared_ptr< ::pr2_controllers_msgs::JointControllerStateArray const> JointControllerStateArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator1> & lhs, const ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.controllestate == rhs.controllestate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator1> & lhs, const ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pr2_controllers_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c47bacaf87f2bc9b8921b0761fb4177e";
  }

  static const char* value(const ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc47bacaf87f2bc9bULL;
  static const uint64_t static_value2 = 0x8921b0761fb4177eULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_controllers_msgs/JointControllerStateArray";
  }

  static const char* value(const ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"JointControllerState[] controllestate\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: pr2_controllers_msgs/JointControllerState\n"
"Header header\n"
"float64 set_point\n"
"float64 process_value\n"
"float64 process_value_dot\n"
"float64 error\n"
"float64 time_step\n"
"float64 command\n"
"float64 p\n"
"float64 i\n"
"float64 d\n"
"float64 i_clamp\n"
"\n"
;
  }

  static const char* value(const ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.controllestate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointControllerStateArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_controllers_msgs::JointControllerStateArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "controllestate[]" << std::endl;
    for (size_t i = 0; i < v.controllestate.size(); ++i)
    {
      s << indent << "  controllestate[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pr2_controllers_msgs::JointControllerState_<ContainerAllocator> >::stream(s, indent + "    ", v.controllestate[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_CONTROLLERS_MSGS_MESSAGE_JOINTCONTROLLERSTATEARRAY_H
