// Generated by gencpp from file pr2_mechanism_controllers/SetProfileResponse.msg
// DO NOT EDIT!


#ifndef PR2_MECHANISM_CONTROLLERS_MESSAGE_SETPROFILERESPONSE_H
#define PR2_MECHANISM_CONTROLLERS_MESSAGE_SETPROFILERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pr2_mechanism_controllers
{
template <class ContainerAllocator>
struct SetProfileResponse_
{
  typedef SetProfileResponse_<ContainerAllocator> Type;

  SetProfileResponse_()
    : time(0.0)  {
    }
  SetProfileResponse_(const ContainerAllocator& _alloc)
    : time(0.0)  {
  (void)_alloc;
    }



   typedef double _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetProfileResponse_

typedef ::pr2_mechanism_controllers::SetProfileResponse_<std::allocator<void> > SetProfileResponse;

typedef boost::shared_ptr< ::pr2_mechanism_controllers::SetProfileResponse > SetProfileResponsePtr;
typedef boost::shared_ptr< ::pr2_mechanism_controllers::SetProfileResponse const> SetProfileResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator1> & lhs, const ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator1> & lhs, const ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pr2_mechanism_controllers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be5310e7aa4c90cdee120add91648cee";
  }

  static const char* value(const ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe5310e7aa4c90cdULL;
  static const uint64_t static_value2 = 0xee120add91648ceeULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_mechanism_controllers/SetProfileResponse";
  }

  static const char* value(const ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time\n"
"\n"
"\n"
;
  }

  static const char* value(const ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetProfileResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_mechanism_controllers::SetProfileResponse_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_MECHANISM_CONTROLLERS_MESSAGE_SETPROFILERESPONSE_H
